import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';

export default async function handlePrompt(bot, msg, promptText, allowedIds, openEditorCommand, logger) {
  const chatId = String(msg.chat.id);

  if (!allowedIds.includes(chatId)) {
    await bot.sendMessage(chatId, 'Unauthorized. /prompt is restricted to the configured ALLOWED_CHAT_ID.');
    logger.warn(`Denied /prompt access for ${chatId}`);
    return;
  }

  if (!promptText || !promptText.trim()) {
    await bot.sendMessage(chatId, 'Usage: /prompt <your GitHub Copilot prompt here>');
    return;
  }

  const filename = 'vibe-copilot-prompt.js';
  const absolutePath = path.resolve(process.cwd(), filename);
  const promptLines = promptText.trim().split(/\r?\n/).map((line) => `// ${line}`);
  const content = `// GitHub Copilot prompt generated by vibecoder-telegram\n` +
    `// Use Copilot to continue this code based on the prompt below.\n` +
    `// ----- Copilot Prompt -----\n` +
    `${promptLines.join('\n')}\n` +
    `// --------------------------\n\n` +
    `// Start writing your code below:\n`;

  await fs.promises.writeFile(absolutePath, content, 'utf8');

  await bot.sendMessage(chatId, `Prompt file created: ${filename}. Opened in editor to continue with GitHub Copilot.`);
  logger.info(`Created Copilot prompt file: ${absolutePath}`);

  exec(`${openEditorCommand} "${absolutePath}"`, (err) => {
    if (err) {
      logger.warn(`Could not open editor with command '${openEditorCommand}': ${err.message}`);
    } else {
      logger.info(`Opened Copilot prompt file in editor: ${absolutePath}`);
    }
  });
};